[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "model/gltf-binary"
